# Docker file for building vala project

FROM nerdiex/base:latest
MAINTAINER Muhammad Sayuti "muhammad.sayuti94@gmail.com"
  
RUN apt-get update
RUN apt-get -qq update
RUN apt-get install -y --no-install-recommends valac meson ninja-build

WORKDIR /projects
